config/routes.rb
Rails.application.routes.draw do

  resources :ideas
  devise_for :users
  resources :entries

  root to: 'static#home'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :entries
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :category
  mount_uploader :avatar, AvatarUploader
  mount_uploader :shoti, AvatarUploader
  mount_uploader :shotii, AvatarUploader
  mount_uploader :shotiii, AvatarUploader
  mount_uploader :thumb, AvatarUploader

  def media?
    category_id == Category.first.id
  end

  def dev?
    category_id == Category.last.id
  end
end

app/models/idea.rb
class Idea < ActiveRecord::Base

  def draft?
    status == 'draft'
  end

  def pub?
    status == 'pub'
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
    role == 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError do |exception|
     redirect_to root_url, alert: exception.message
   end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, :except => [:index, :new, :create, :dev, :media]

  def index
    @entries = Entry.all
  end

  def new
    @entry = Entry.new
    authorize @entry
  end

  def edit
    authorize @entry
  end

  def show
  end

  def create
    @entry = Entry.new(entry_params)

    authorize @entry
    if @entry.save
      flash[:notice] = "Entry created."
      redirect_to @entry
    else
      flash[:error] = "Entry was not created, please try again."
      render :new
    end
  end

  def update
    authorize @entry
    if @entry.update_attributes(entry_params)
      flash[:notice] = "Entry updated."
      redirect_to @entry
    else
      flash[:error] = "Entry was not updated, please try again."
      render :edit
    end
  end

  def destroy
    authorize @entry
    if @entry.destroy
      flash[:notice] = "Entry was deleted."
      redirect_to entries_path
    else
      flash[:error] = "Entry was not deleted, please try again."
      redirect_to :back
    end
  end

  private

  def set_entry
    @entry = Entry.friendly.find(params[:id])
  end

  def entry_params
    params.require(:entry).permit(:title, :tagline, :body, :category_id, :avatar, :shoti, :shotii, :shotiii, :thumb)
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, :except => [:index, :new, :create]

  def index
    @ideas = Idea.all
    authorize @ideas
  end

  def new
    @idea = Idea.new
    authorize @idea
  end

  def edit
    authorize @idea
  end

  def show
    authorize @idea
  end

  def create
    @idea = Idea.new(idea_params)

    authorize @idea
    if @idea.save
      flash[:notice] = "Idea created."
      redirect_to @idea
    else
      flash[:error] = "Idea was not created, please try again."
      render :new
    end
  end

  def update
    authorize @idea
    if @idea.update_attributes(idea_params)
      flash[:notice] = "Idea updated."
      redirect_to @idea
    else
      flash[:error] = "Idea was not updated, please try again."
      render :edit
    end
  end

  def destroy
    authorize @idea
    if @idea.destroy
      flash[:notice] = "Idea deleted."
      redirect_to ideas_path
    else
      flash[:error] = "Idea was not deleted, please try again."
      render :back
    end
  end

  private

  def set_idea
    @idea = Idea.find(params[:id])
  end

  def idea_params
    params.require(:idea).permit(:title, :tagline, :status, :body)
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def home
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

  def markdown_to_html(markdown)
    renderer = Redcarpet::Render::HTML.new
    extensions = {fenced_code_blocks: true}
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
    (redcarpet.render markdown).html_safe
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/entries/_form.html.erb
<%= form_for @entry do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :tagline %>
    <%= f.text_field :tagline, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :category %>
    <%= f.select :category_id, options_from_collection_for_select(Category.all, "id", "title") %>
  </div>

  <div class="form-group">
   <%= f.label :thumb %>
   <%= f.file_field :thumb %>
   <%= f.hidden_field :thumb_cache %>
  </div>
  <div class="form-group">
   <%= f.label :main %>
   <%= f.file_field :avatar %>
   <%= f.hidden_field :avatar_cache %>
  </div>
  <div class="form-group">
    <%= f.label :first_shot %>
    <%= f.file_field :shoti %>
    <%= f.hidden_field :shoti_cache %>
  </div>
  <div class="form-group">
    <%= f.label :second_shot %>
    <%= f.file_field :shotii %>
    <%= f.hidden_field :shotii_cache %>
  </div>
  <div class="form-group">
    <%= f.label :third_shot %>
    <%= f.file_field :shotiii %>
    <%= f.hidden_field :shotiii_cache %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class:'form-control', rows:'5' %>
  </div>

  <div class="form-group">
    <%= f.submit 'Save', class: 'btn btn-lg' %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<% if policy(@entry).edit? %>
<h1>Edit</h1>
<%= render 'form' %>
<% end %>

app/views/entries/index.html.erb
<h1>Entries#index</h1>
<% @entries.each do |entry| %>
  <p><%= link_to entry.title, entry %></p>
<% end %>

app/views/entries/new.html.erb
<% if policy(@entry).new? %>
  <h1>New Entry</h1>
  <%= render 'form' %>
<% end %>

app/views/entries/show.html.erb
<div id="entry-show">
  <h3 class="title"><%= @entry.title %></h3>
  <hr class="title-hr">
  <h1 class="tagline"><%= @entry.tagline %></h1>
  <div class="header-shot">

    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
      </ol>

      <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <% if @entry.avatar? %>
        <%= image_tag(@entry.avatar.url) %>
      <% else %>
        <%= image_tag("exampleshot.png") %>
      <% end %>
    </div>
    <div class="item">
      <% if @entry.shoti? %>
        <%= image_tag(@entry.shoti.url) %>
      <% else %>
        <%= image_tag("exampleshot.png") %>
      <% end %>
    </div>
    <div class="item">
      <% if @entry.shotii? %>
        <%= image_tag(@entry.shotii.url) %>
      <% else %>
        <%= image_tag("exampleshot.png") %>
      <% end %>
    </div>

    <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
  </div>

  <div class="entry-body">
    <p><%= markdown_to_html @entry.body %></p>
  </div>


  <div class="bottom-nav">
    <hr>
    <h3>
      <%= mail_to 'ching@casanovatapia.com', 'Contact me' %>
      or
      <%= link_to 'previous page', :back %>
    </h3>
  </div>
  
  <p class="small">
    <% if policy(@entry).edit? %>
      <%= link_to 'Edit', edit_entry_path(@entry) %>
      <%= link_to 'Delete', @entry, :method => :delete, :data => { :confirm => 'Are you sure?' } %>
    <% end %>
  </p>

</div>

app/views/ideas/_form.html.erb
<%= form_for @idea do |f| %>
  <div class="form-group">
    <%= f.label :status %>
    <%= f.text_field :status, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :tagline %>
    <%= f.text_field :tagline, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class:'form-control', rows:'5' %>
  </div>

  <div class="form-group">
    <%= f.submit 'Save', class: 'btn btn-lg' %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<% if policy(@idea).edit? %>
  <h1>Edit</h1>
  <%= render 'form' %>
<% end %>

app/views/ideas/index.html.erb
<div id="ideas">
  <h1 class="header">I sometimes publish my thoughts here</h1>

  <div class="idea-list">
    <% @ideas.each do |idea| %>
      <% if policy(idea).show? %>
        <%= link_to idea do %>
          <div class="idea">
            <h4><%= idea.title %></h4>
            <hr>
            <h2><%= idea.tagline %></h2>
          </div>
        <% end %>
        <% if policy(idea).edit? %>
          <%= link_to 'Edit', edit_idea_path(idea) %>
          <%= link_to 'Delete', idea, :method => :delete, :data => { :confirm => 'Are you sure?' } %>
        <% end %>
      <% end %>
    <% end %>
  </div>

  <div class="bottom-nav">
    <hr>
    <h3>
      <%= mail_to 'ching@casanovatapia.com', 'Contact me' %>
      or
      <%= link_to 'previous page', :back %>
    </h3>
    <% if policy(@ideas).new? %>
      <%= link_to 'New Idea!', new_idea_path %>
    <% end %>
  </div>
</div>

app/views/ideas/new.html.erb
<% if policy(@idea).new? %>
  <h1>New Idea!</h1>
  <%= render 'form' %>
<% end %>

app/views/ideas/show.html.erb
<% if policy(@idea).show? %>
  <div id="idea-show">
    <h5 class="date"><%= @idea.created_at.strftime("%d %B %Y") %></h5>
    <h3 class="title"><%= @idea.title %></h3>
    <hr>
    <h1 class="tagline"><%= @idea.tagline %></h1>

    <div class="idea-body">
      <p><%= markdown_to_html @idea.body %></p>
    </div>

  <div class="bottom-nav">
    <hr>
    <h3>
      <%= mail_to 'ching@casanovatapia.com', 'Contact me' %>
      or
      <%= link_to 'previous page', :back %>
    </h3>
    <p class="small">
      <% if policy(@idea).edit? %>
        <%= link_to 'Edit', edit_idea_path(@idea) %>
        <%= link_to 'Delete', @idea, :method => :delete, :data => { :confirm => 'Are you sure?' } %>
      <% end %>
    </p>
  </div>

  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Provisionners</title>
  <meta name="description" content="The Provisonners is a creative group based in Los Angeles. We provide resources for emerging talent.">
  <meta name="keywords" content="los angeles, heart winner, the provisionners, provisionner, talent, creative, emerging talent, developer, web developer, merchandising, ching casanova tapia, ching tapia, casanova, ching, casanova tapia, talent, collaboration">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
<body>
<div id="container">
  <div id="header">
    <!-- <nav class="navbar navbar-default navbar-fixed-top">
      <%= link_to(root_path) do %>
        <%= image_tag("text-black.png") %>
      <% end %> -->
      <!-- <div class="btn-group">
        <button type="button" class="btn btn-nav dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="caret"></span>
          <span class="caret"></span>
          <span class="caret"></span>
          <span class="caret"></span>
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
          <li><a href="#">Action</a></li>
          <li><a href="#">Another action</a></li>
          <li><a href="#">Something else here</a></li>
          <li role="separator" class="divider"></li>
          <li><a href="#">Separated link</a></li>
        </ul>
      </div> -->
    <!-- </nav> -->
    <!-- Flash messages  -->
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>
  </div>
  <div id="body">

    <%= yield %>

  </div>


  <div id="footer">
    <p class="small text-center">
      <%= image_tag("ct-white.png") %> 2016.
    </p>
  </div>

</div>
</body>
</html>